In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.20.3


In [4]:
data = [[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]
data

[[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]

In [6]:
a = np.array(data)
a

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [7]:
def print_info(a):
    print("number elements: ", a.size)
    print("number of dimnesions: ", a.ndim)
    print("shape: ", a.shape)
    print("data type: ", a.dtype)
    print("strides: ", a.strides)
    print("flags: ")
    print(a.flags)
    
print_info(a)

number elements:  12
number of dimnesions:  2
shape:  (3, 4)
data type:  int32
strides:  (16, 4)
flags: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [8]:
print(a.data)

In [11]:
abytes = a.ravel().view(dtype=np.uint8)

In [13]:
print(abytes[:24])

[100   0   0   0 200   0   0   0  50   0   0   0 144   1   0   0  50   0
   0   0   0   0   0   0]


In [14]:
print_info(abytes)

number elements:  48
number of dimnesions:  1
shape:  (48,)
data type:  uint8
strides:  (1,)
flags: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [15]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
a = np.zeros((5,4), dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
a.dtype

dtype('int32')

In [25]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones((4,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
np.full((3,3), fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
np.full((10,10), fill_value=10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [34]:
"""empty, unlike zeros, does not set the array values to zero, and may 
therefore be marginally faster. On the other hand, it requires the user
to manually set all the values in the array, and should be used with 
caution."""

np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.94855038e-321, 1.42410974e-306,
        8.34451927e-308]])

In [40]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
np.eye(5, dtype=int, k=1) # changing index

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [41]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [42]:
np.linspace(0, np.pi, 5)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [44]:
np.random.random((3,3))

array([[0.20221478, 0.38628016, 0.81043605],
       [0.32699125, 0.09734076, 0.51719083],
       [0.36893317, 0.47050142, 0.71908628]])

In [45]:
np.random.normal(0,1,(3,4))

array([[ 0.32363318,  0.2929084 ,  0.81586014,  1.81681076],
       [ 0.31460792,  2.08406485, -1.43147306,  0.92672242],
       [-0.31232314, -0.9251697 ,  1.70145629,  1.40144636]])

In [47]:
np.random.randint(-2, 10, (3,4))

array([[ 8,  4,  9, -2],
       [-1,  1, -1,  7],
       [ 3,  5,  7,  9]])

In [48]:
np.random.random((10,10))

array([[0.77184649, 0.66914605, 0.07688599, 0.0247964 , 0.98471532,
        0.23039298, 0.63699309, 0.74114078, 0.42138626, 0.03698045],
       [0.22339673, 0.37436381, 0.02855217, 0.8450493 , 0.90587375,
        0.43977665, 0.88459519, 0.28185833, 0.96085841, 0.43806607],
       [0.03735999, 0.37618019, 0.2052192 , 0.44865108, 0.81984109,
        0.33321545, 0.10574584, 0.41656043, 0.56766171, 0.64539533],
       [0.37298213, 0.68326816, 0.35828728, 0.11630758, 0.9097666 ,
        0.55191928, 0.85761802, 0.86162786, 0.49325193, 0.22432317],
       [0.5081541 , 0.08160825, 0.60367038, 0.97958657, 0.84363573,
        0.29940811, 0.07693635, 0.5770806 , 0.52797718, 0.82798135],
       [0.16986603, 0.24843141, 0.73186032, 0.88361277, 0.22799732,
        0.95340978, 0.5001484 , 0.85755378, 0.57644614, 0.40138905],
       [0.31962795, 0.6147332 , 0.14797971, 0.35951427, 0.06337906,
        0.33201168, 0.48610334, 0.33806133, 0.83694453, 0.37799568],
       [0.1793195 , 0.5266647 , 0.5971787

In [54]:
np.random.normal(0, 2, (10,2))

array([[ 2.22637941, -4.54693771],
       [-0.85149682, -1.80292478],
       [-0.70712716,  0.22435459],
       [-0.84596368, -1.61800602],
       [ 1.9763696 ,  0.11387405],
       [-0.39058278,  1.53631568],
       [-0.71160141,  0.21902054],
       [-0.29707343,  0.01715041],
       [-1.10294184, -3.18918507],
       [ 2.54916288,  2.01186565]])

In [58]:
np.random.seed(2)
print(np.random.randint(0,100,10))
print(np.random.normal(0, 1, 10))

[40 15 72 22 43 82 75  7 34 49]
[ 0.50288142 -1.24528809 -1.05795222 -0.90900761  0.55145404  2.29220801
  0.04153939 -1.11792545  0.53905832 -0.5961597 ]


In [59]:
np.random.seed(2)
print(np.random.randint(0,100,10))
print(np.random.normal(0, 1, 10))

[40 15 72 22 43 82 75  7 34 49]
[ 0.50288142 -1.24528809 -1.05795222 -0.90900761  0.55145404  2.29220801
  0.04153939 -1.11792545  0.53905832 -0.5961597 ]


In [60]:
new_generator = np.random.RandomState(seed=123)
new_generator.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [61]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [62]:
b = np.array([[1,2,3], [3,4,5]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int32:
[[1 2 3]
 [3 4 5]]


In [63]:
print_info(a)

number elements:  20
number of dimnesions:  2
shape:  (5, 4)
data type:  int32
strides:  (16, 4)
flags: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [65]:
c = np.array([b,b])
info("c", c)

c has dim 3, shape (2, 2, 3), size 12, and dtype int32:
[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]
