In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.20.3


In [4]:
data = [[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]
data

[[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]

In [5]:
a = np.array(data)
a

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [6]:
def print_info(a):
    print("number elements: ", a.size)
    print("number of dimnesions: ", a.ndim)
    print("shape: ", a.shape)
    print("data type: ", a.dtype)
    print("strides: ", a.strides)
    print("flags: ")
    print(a.flags)
    
print_info(a)

number elements:  12
number of dimnesions:  2
shape:  (3, 4)
data type:  int32
strides:  (16, 4)
flags: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [7]:
print(a.data)

In [8]:
abytes = a.ravel().view(dtype=np.uint8)

In [9]:
print(abytes[:24])

[100   0   0   0 200   0   0   0  50   0   0   0 144   1   0   0  50   0
   0   0   0   0   0   0]


In [10]:
print_info(abytes)

number elements:  48
number of dimnesions:  1
shape:  (48,)
data type:  uint8
strides:  (1,)
flags: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [11]:
np.array([1,2,3])

array([1, 2, 3])

In [12]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
a = np.zeros((5,4), dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
a.dtype

dtype('int32')

In [17]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((4,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
np.full((3,3), fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
np.full((10,10), fill_value=10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [21]:
"""empty, unlike zeros, does not set the array values to zero, and may 
therefore be marginally faster. On the other hand, it requires the user
to manually set all the values in the array, and should be used with 
caution."""

np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.73905541e-321, 1.24610723e-306,
        1.69119873e-306]])

In [22]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
np.eye(5, dtype=int, k=1) # changing index

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [41]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [42]:
np.linspace(0, np.pi, 5)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [44]:
np.random.random((3,3))

array([[0.20221478, 0.38628016, 0.81043605],
       [0.32699125, 0.09734076, 0.51719083],
       [0.36893317, 0.47050142, 0.71908628]])

In [45]:
np.random.normal(0,1,(3,4))

array([[ 0.32363318,  0.2929084 ,  0.81586014,  1.81681076],
       [ 0.31460792,  2.08406485, -1.43147306,  0.92672242],
       [-0.31232314, -0.9251697 ,  1.70145629,  1.40144636]])

In [47]:
np.random.randint(-2, 10, (3,4))

array([[ 8,  4,  9, -2],
       [-1,  1, -1,  7],
       [ 3,  5,  7,  9]])

In [48]:
np.random.random((10,10))

array([[0.77184649, 0.66914605, 0.07688599, 0.0247964 , 0.98471532,
        0.23039298, 0.63699309, 0.74114078, 0.42138626, 0.03698045],
       [0.22339673, 0.37436381, 0.02855217, 0.8450493 , 0.90587375,
        0.43977665, 0.88459519, 0.28185833, 0.96085841, 0.43806607],
       [0.03735999, 0.37618019, 0.2052192 , 0.44865108, 0.81984109,
        0.33321545, 0.10574584, 0.41656043, 0.56766171, 0.64539533],
       [0.37298213, 0.68326816, 0.35828728, 0.11630758, 0.9097666 ,
        0.55191928, 0.85761802, 0.86162786, 0.49325193, 0.22432317],
       [0.5081541 , 0.08160825, 0.60367038, 0.97958657, 0.84363573,
        0.29940811, 0.07693635, 0.5770806 , 0.52797718, 0.82798135],
       [0.16986603, 0.24843141, 0.73186032, 0.88361277, 0.22799732,
        0.95340978, 0.5001484 , 0.85755378, 0.57644614, 0.40138905],
       [0.31962795, 0.6147332 , 0.14797971, 0.35951427, 0.06337906,
        0.33201168, 0.48610334, 0.33806133, 0.83694453, 0.37799568],
       [0.1793195 , 0.5266647 , 0.5971787

In [54]:
np.random.normal(0, 2, (10,2))

array([[ 2.22637941, -4.54693771],
       [-0.85149682, -1.80292478],
       [-0.70712716,  0.22435459],
       [-0.84596368, -1.61800602],
       [ 1.9763696 ,  0.11387405],
       [-0.39058278,  1.53631568],
       [-0.71160141,  0.21902054],
       [-0.29707343,  0.01715041],
       [-1.10294184, -3.18918507],
       [ 2.54916288,  2.01186565]])

In [58]:
np.random.seed(2)
print(np.random.randint(0,100,10))
print(np.random.normal(0, 1, 10))

[40 15 72 22 43 82 75  7 34 49]
[ 0.50288142 -1.24528809 -1.05795222 -0.90900761  0.55145404  2.29220801
  0.04153939 -1.11792545  0.53905832 -0.5961597 ]


In [59]:
np.random.seed(2)
print(np.random.randint(0,100,10))
print(np.random.normal(0, 1, 10))

[40 15 72 22 43 82 75  7 34 49]
[ 0.50288142 -1.24528809 -1.05795222 -0.90900761  0.55145404  2.29220801
  0.04153939 -1.11792545  0.53905832 -0.5961597 ]


In [60]:
new_generator = np.random.RandomState(seed=123)
new_generator.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [61]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [62]:
b = np.array([[1,2,3], [3,4,5]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int32:
[[1 2 3]
 [3 4 5]]


In [63]:
print_info(a)

number elements:  20
number of dimnesions:  2
shape:  (5, 4)
data type:  int32
strides:  (16, 4)
flags: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [65]:
c = np.array([b,b])
info("c", c)

c has dim 3, shape (2, 2, 3), size 12, and dtype int32:
[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]


In [66]:
d = np.array([c,c])
info("d", d)

d has dim 4, shape (2, 2, 2, 3), size 24, and dtype int32:
[[[[1 2 3]
   [3 4 5]]

  [[1 2 3]
   [3 4 5]]]


 [[[1 2 3]
   [3 4 5]]

  [[1 2 3]
   [3 4 5]]]]


In [24]:
a = np.array([1,4,2,7,9,5])
print(a[1])

4


In [25]:
print(a[-2])

9


In [29]:
b=np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [30]:
print(b[1,2])

6


In [32]:
print(b[0,1])
print(b[0,-1]) 

2
3


In [34]:
b[0,0] = b[0,0] * 3
print(b)

[[9 2 3]
 [4 5 6]]


In [36]:
print(b[0])  
print(b[1]) 

[9 2 3]
[4 5 6]


In [40]:
print(a)
print(a[1:3])
print(a[::-1])

[1 4 2 7 9 5]
[4 2]
[5 9 7 2 4 1]


In [53]:
print(b)
print(b[:,0])

[[9 2 3]
 [4 5 6]]
[9 4]


In [54]:
print(b[0,:])

[9 2 3]


In [55]:
print(b[:,1:])

[[2 3]
 [5 6]]


In [56]:
b[:,1:] = 7
print(b)

[[9 7 7]
 [4 7 7]]


In [61]:
print(b[:,1:3])    # First column
print(b[0:2,:])  

[[7 7]
 [7 7]]
[[9 7 7]
 [4 7 7]]


In [64]:
a = np.random.randint(0,10,(5,5))
print(a)

[[7 4 5 1 7]
 [3 8 6 1 6]
 [5 8 7 8 4]
 [5 7 7 2 8]
 [8 0 5 8 3]]


In [69]:
print(a[:,-1])
print(a[1:4,2:4])

[7 6 4 8 3]
[[6 1]
 [7 8]
 [7 2]]


In [70]:
a[1:4,2:4] = 100

[[  7   4   5   1   7]
 [  3   8 100 100   6]
 [  5   8 100 100   4]
 [  5   7 100 100   8]
 [  8   0   5   8   3]]


In [72]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
a2 = a.reshape(3,3)
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
d = np.arange(4)
print(d)
dr = d.reshape(1,4)
print(dr)
dc = d.reshape(4,1)
print(dc)
dd = d.reshape(2,2)
print(dd)

[0 1 2 3]
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]
[[0 1]
 [2 3]]


In [84]:
print(d)
print(d[:, np.newaxis])
print(d[np.newaxis:,])

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
[0 1 2 3]


In [86]:
a = np.random.randint(0, 10 , (4,4))
print(a)
print(a.T)

[[1 9 7 6]
 [5 2 0 6]
 [0 5 9 7]
 [8 0 2 8]]
[[1 5 0 8]
 [9 2 5 0]
 [7 0 9 2]
 [6 6 7 8]]


In [88]:
a = np.arange(2)
a

array([0, 1])

In [89]:
b = np.arange(2,5)
b

array([2, 3, 4])

In [90]:
print(a.shape)
print(b.shape)

(2,)
(3,)


In [92]:
np.concatenate((a,b))

array([0, 1, 2, 3, 4])

In [93]:
c = np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [103]:
x = np.concatenate((c,c,c))
x

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [104]:
y = np.concatenate((c,c), axis=1)
y

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [107]:
z= np.concatenate((y,y,y))
z

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [111]:
np.concatenate(((y,z)))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [117]:
print(b)
t = np.stack((b,b))
t

[2 3 4]


array([[2, 3, 4],
       [2, 3, 4]])

In [118]:
np.stack((t,t))

array([[[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]]])

In [119]:
d = np.arange(12).reshape(6,2)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [120]:
d1, d2 = np.split(d,2)
print(d1)
print(d2)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [121]:
d4, d5 = np.split(d,2, axis=1)

In [122]:
print(d4)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


In [126]:
print(d4.ndim)
print(d4.dtype)
print(d4.shape)
print(d4.itemsize)
print(d4.size)
print(d4.nbytes)

2
int32
(6, 1)
4
6
24


In [127]:
d = np.arange(12).reshape(2,6)
print(d)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [128]:
parts=np.split(d, (2,3,5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)

part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


In [129]:
tiheydet = np.array([0.81, 0.75, 0.88, 0.94, 1.08, 1.24, 2.34, 1.00])
tiheydet[3]

0.94

In [130]:
L = [1,5.2, "ab"]
L2 = []
for x in L:
    L2.append(x*2)
print(L2)

[2, 10.4, 'abab']


In [131]:
L = np.array(L)
L

array(['1', '5.2', 'ab'], dtype='<U32')

In [139]:
a=[2.1, 5.0, 17.2]
print(type(a[0]))
a = np.array(a)
print(a.dtype)
a2=a*2
print(a2)

<class 'float'>
float64
[ 4.2 10.  34.4]


In [140]:
b = np.array([-1, 3.2, 2.4])
print(-a**2*b)

[   4.41   -80.    -710.016]


In [141]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


In [143]:
np.random.seed(0)
a = np.random.randint(-100, 100, (4,5))
print(a)

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]


In [149]:
print(a[:,0].min())
print(a.max())
print(a.sum())
print(a[1].mean())

-13
95
-17
-27.2


In [150]:
np.random.seed(9)
b = np.random.randint(0,10,(3,4))
print(b)

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]


In [151]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[ 7 20 17 15]
[25 19 15]


In [152]:
g = np.array([1,2,3,10])
np.prod(g)

60

In [159]:
np.any([False, False, False, True, False])

True

In [163]:
a = np.arange(1000)
%timeit np.sum(a)

7.35 µs ± 63.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [164]:
%timeit sum(a)

80.2 µs ± 804 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [165]:
a = np.arange(3)
a

array([0, 1, 2])

In [166]:
b = np.array([4])
b

array([4])

In [167]:
a + b

array([4, 5, 6])

In [168]:
np.arange(3) + 4

array([4, 5, 6])

In [169]:
a= np.full((3,3), 5)
b = np.arange(3)
print("a:", a, sep="\n")
print("b:", b)

a:
[[5 5 5]
 [5 5 5]
 [5 5 5]]
b: [0 1 2]


In [170]:
print("a+b:", a+b, sep="\n")

a+b:
[[5 6 7]
 [5 6 7]
 [5 6 7]]


In [171]:

a=np.arange(3)
b=np.arange(3).reshape((3,1))
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [172]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [174]:
broadcasted_a, broadcasted_b = np.broadcast_arrays(a,b)
print(broadcasted_a)
print(broadcasted_b)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [175]:
a=np.array([1,2,3])
b=np.array([4,5])
try:
    a+b
except ValueError as e:
    import sys
    print(e, file=sys.stderr)

operands could not be broadcast together with shapes (3,) (2,) 
