In [1]:
import numpy as np

In [2]:
# comparison

a = np.array([1,3,4])
b = np.array([2,2,7])
c = a < b
print(c)

[ True False  True]


In [3]:
# aLL or some True?

print(c.all())   
print(c.any())

False
True


In [4]:
# How many is True?

print(np.sum(c))

2


In [5]:
# Comparison has broadcasting rules

print(a > 0)

[ True  True  True]


In [8]:
# daily average temperatures from year 2017 from Kumpula weather station
import pandas as pd
a=pd.read_csv("https://raw.githubusercontent.com/csmastersUH/data_analysis_with_python_2020/master/kumpula-weather-2017.csv")['Air temperature (degC)'].values
a

array([  0.6,  -3.9,  -6.5, -12.8, -17.8, -17.8,  -3.8,  -0.5,   0.5,
         1.7,  -1.6,  -2.8,   1.1,   0.8,  -2.8,  -4.2,  -3.5,   1.1,
         1.6,  -0.6,  -1.8,   1. ,   0.1,  -2.2,  -3.8,   1.9,   1.6,
         0.8,   0.6,   1. ,   0.2,  -0.6,  -0.8,  -0.2,   0.4,  -2.5,
        -7.3, -12.1,  -8.8, -10.1,  -8.3,  -5.4,  -2.7,   1.5,   4.4,
         0. ,   0.5,   1.5,   1.9,   2.2,   0.4,  -2.5,  -4.6,  -0.7,
        -5.3,  -5.6,  -2. ,  -2.3,   2.1,   1.5,   1.5,   0.9,  -1.8,
        -4.2,  -4.2,  -2.9,   0.2,   1.2,   1.4,   2.2,  -0.9,   0.6,
         0.6,   3.8,   3.4,   2. ,   1.6,   0.6,   0.2,   1.6,   2.3,
         2.5,   0.5,   1.9,   4.8,   6.6,   2.4,   0.4,  -0.4,   0.2,
         1.5,   4.3,   3. ,   3.8,   3.3,   4.7,   4.1,   3.3,   3.7,
         6. ,   4.3,   1.8,   1.2,  -0.5,  -1.4,  -1.7,   0.6,   0.3,
         1.2,   2.5,   5.7,   3.1,   2.9,   3.6,   2.8,   3.2,   4.4,
         4.1,   2.3,   2.2,   7.6,   9.4,   9.2,   6.7,  10.1,  11.1,
         6.1,   4.4,

In [9]:
print("Number of days with the temperature below zero:", np.sum(a < 0))

Number of days with the temperature below zero 49


In [10]:
# Here we have to use parentheses, because precedence of the & is higher than that of <
np.sum((0 < a) & (a < 10))  

185

In [12]:
np.sum(a > 10)

128

In [13]:
# Print only the first ten elements boolean value True if value > 0
c = a > 0
print(c[:10])    


[ True False False False False False False False  True  True]


In [14]:
# Prints values higher than zero
print(a[c]) 

[ 0.6  0.5  1.7  1.1  0.8  1.1  1.6  1.   0.1  1.9  1.6  0.8  0.6  1.
  0.2  0.4  1.5  4.4  0.5  1.5  1.9  2.2  0.4  2.1  1.5  1.5  0.9  0.2
  1.2  1.4  2.2  0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3  2.5
  0.5  1.9  4.8  6.6  2.4  0.4  0.2  1.5  4.3  3.   3.8  3.3  4.7  4.1
  3.3  3.7  6.   4.3  1.8  1.2  0.6  0.3  1.2  2.5  5.7  3.1  2.9  3.6
  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1  6.1  4.4
  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9 14.7 14.6
 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.   9.9 10.4
 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3 16.9 17.8
 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1 16.4 14.5
 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7 18.  15.4
 15.  13.7 14.6 15.8 15.6 16.9 15.7 16.1 17.2 19.  19.1 17.8 18.3 17.8
 18.9 17.5 18.2 16.6 17.1 16.  15.2 17.2 18.3 18.7 18.1 19.6 17.4 16.1
 16.4 17.6 19.  18.  18.2 17.4 16.2 14.9 13.5 12.9 11.2 10.4 10.7 12.
 14.4 16

In [15]:
# Masking out all the negative values to zeros

a[~c] = 0
print(a)

[ 0.6  0.   0.   0.   0.   0.   0.   0.   0.5  1.7  0.   0.   1.1  0.8
  0.   0.   0.   1.1  1.6  0.   0.   1.   0.1  0.   0.   1.9  1.6  0.8
  0.6  1.   0.2  0.   0.   0.   0.4  0.   0.   0.   0.   0.   0.   0.
  0.   1.5  4.4  0.   0.5  1.5  1.9  2.2  0.4  0.   0.   0.   0.   0.
  0.   0.   2.1  1.5  1.5  0.9  0.   0.   0.   0.   0.2  1.2  1.4  2.2
  0.   0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3  2.5  0.5  1.9
  4.8  6.6  2.4  0.4  0.   0.2  1.5  4.3  3.   3.8  3.3  4.7  4.1  3.3
  3.7  6.   4.3  1.8  1.2  0.   0.   0.   0.6  0.3  1.2  2.5  5.7  3.1
  2.9  3.6  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1
  6.1  4.4  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9
 14.7 14.6 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.
  9.9 10.4 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3
 16.9 17.8 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1
 16.4 14.5 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7
 18.  15.

In [18]:
ar = np.array([[8, 9, 3, 8, 8],
[0, 5, 3, 9, 9],
[5, 7, 6, 0, 4],
[7, 8, 1, 6, 2],
[2, 1, 3, 5, 8]])
ar

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2],
       [2, 1, 3, 5, 8]])

In [24]:
comp = ar[:,1] > ar[:,-1]


[ True False  True  True False] [0 5 3 9 9] [2 1 3 5 8]


In [25]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [26]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [27]:
a = np.array([[1, 3, 4, 2],
              [2, 2, 1, 2]])

In [33]:
row_length = len(a[1,])

In [48]:
half = int(row_length / 2)

In [65]:
b = sum(a[:,0:half]) > sum(a[:,half-1:-1]) 
left = a[:,0:half].sum(axis=1)
right = a[:,half-1:-1].sum(axis=1)
c = left > right
a[c]

array([[2, 2, 1, 2]])

In [2]:
# Indexing

np.random.seed(0)
a = np.random.randint(0, 20, 20)
a2 = np.array([a[2], a[5], a[7]])
print(a)
print(a2)

[12 15  0  3  3  7  9 19 18  4  6 12  1  6  7 14 17  5 13  8]
[ 0  7 19]


In [3]:
# fancy indexing

idx = [2, 5, 7]
print(a[idx])
print(a[[2, 5, 7]])

[ 0  7 19]
[ 0  7 19]


In [4]:
a[idx] = -1
a

array([12, 15, -1,  3,  3, -1,  9, -1, 18,  4,  6, 12,  1,  6,  7, 14, 17,
        5, 13,  8])

In [5]:
# also in higher dimension arrays

b = np.arange(16).reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
row = np.array([0,2])
col = np.array([1,3])
print(b[row, col])

[ 1 11]


In [7]:
# Shape of the result array is defined by the shape on the index arrays!

row2 = np.array([[0,0], [2,2]])
col2 = np.array([[1,3], [1,3]])
print(row2)
print(col2)
print(b[row2, col2])

[[0 0]
 [2 2]]
[[1 3]
 [1 3]]
[[ 1  3]
 [ 9 11]]


In [8]:
# Relying to the broadcating rules.

row2=row.reshape(2,1)   # has shape (2, 1)
col2=col.reshape(1,2)   # has shape (1, 2)
print(row2)
print(col2)
print(b[row2, col2]) 

[[0]
 [2]]
[[1 3]]
[[ 1  3]
 [ 9 11]]


In [9]:
# Combining indexing, slicing and fancy indexing:

b[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [11]:
# Does not sort the agument

a = np.array([2,1,4,3,5])
print(np.sort(a))
print(a)

[1 2 3 4 5]
[2 1 4 3 5]


In [12]:
# Modifies the argument

a.sort()
print(a)

[1 2 3 4 5]


In [13]:
b = np.random.randint(0,10, (4,4))
b

array([[9, 4, 3, 0],
       [3, 5, 0, 2],
       [3, 8, 1, 3],
       [3, 3, 7, 0]])

In [14]:
# Sorting columns
np.sort(b, axis=0)

array([[3, 3, 0, 0],
       [3, 4, 1, 0],
       [3, 5, 3, 2],
       [9, 8, 7, 3]])

In [15]:
# Sorting rows
np.sort(b, axis=1)

array([[0, 3, 4, 9],
       [0, 2, 3, 5],
       [1, 3, 3, 8],
       [0, 3, 3, 7]])

In [16]:
# argsort returns array of incides of the sorted elements

a=np.array([23,12,47,35,59])
print("Array a:", a)
idx = np.argsort(a)
print("Indices:", idx)

Array a: [23 12 47 35 59]
Indices: [1 0 3 2 4]
