In [2]:
import numpy as np

In [2]:
# One dimensional array
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# Two dimensional array
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Three dimensional array 
np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
# Create a 0-array
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# initializes all elements to one
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Change the datatype float -> int
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
np.full((2,3), fill_value=7)

array([[7, 7, 7],
       [7, 7, 7]])

In [9]:
np.empty((2,4))

array([[0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 5.6718736e-321, 1.2461147e-306, 0.0000000e+000]])

In [10]:
# eye creates a identity matrix
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [11]:
# arange creates an array (not a list like range)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, np.pi, 5) 

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [13]:
np.random.random((3,4))    

array([[0.51873978, 0.1841213 , 0.33758214, 0.5092622 ],
       [0.50047335, 0.75850964, 0.35587859, 0.33767982],
       [0.89510042, 0.81597671, 0.21911388, 0.31630926]])

In [14]:
# mean = 0, standard deviation = 1:
np.random.normal(0, 1, (3,4))

array([[ 0.557334  ,  0.96556386,  1.79053921, -0.05218513],
       [-0.27783934,  2.00224557,  1.56633291,  1.35287683],
       [ 1.3512305 , -0.08182338, -1.86826899,  1.57320417]])

In [17]:
# uniformly distributed integers from the half-open interval [-2,10)
np.random.randint(-2, 10, (20,15))  

array([[ 0, -2,  9,  1,  1,  0, -2,  6,  6, -1,  0, -1,  7,  8,  6],
       [ 8,  1, -2,  7,  1,  5,  6,  6, -2, -1,  8,  4,  1,  9,  4],
       [ 9,  5,  1,  7,  2,  8,  6,  2,  0,  0,  0,  7, -2,  1,  0],
       [ 8,  8,  9,  1,  3,  7,  6,  7,  1,  1,  9,  1,  8,  0,  7],
       [ 2, -1,  7,  4,  9,  4,  9,  3,  0,  2,  9,  4,  2,  1, -2],
       [-1,  5,  8,  5,  7,  5, -1,  0,  6,  5,  6,  0, -1,  1,  0],
       [ 1,  7,  1,  2,  6,  6,  7,  1,  1,  3,  2,  9,  4,  8,  5],
       [ 0, -1,  7,  2, -2,  7, -2,  2,  3,  1,  3,  4,  8,  8,  1],
       [ 7,  7,  8,  5, -1,  2,  1,  6,  3, -1,  0,  3,  7,  1,  7],
       [ 5,  0, -1,  2,  5,  9,  5,  5,  4,  5,  8,  3,  2, -2,  1],
       [-1,  6, -2,  2,  1, -1,  7,  4,  0,  1, -2,  7,  4,  3,  1],
       [ 6, -2,  0,  4,  9, -2,  1, -1,  9,  5,  5,  7,  6,  0,  4],
       [ 2,  0,  6,  6, -1, -2,  4,  6,  7,  9, -2,  4,  2,  3,  5],
       [-2,  4,  8,  4,  4,  6,  9,  1,  9,  7,  9,  7,  1,  0,  2],
       [ 1,  3, -2,  8,  1, -2,  5

In [22]:
# random numbers deterministically
np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


In [24]:
new_generator = np.random.RandomState(seed=123)  # RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [7]:
# Array types and attributes... Let's create info function:

def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [26]:
b=np.array([[1,2,3], [4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int32:
[[1 2 3]
 [4 5 6]]


In [27]:
 # Creates a 3-dimensional array because b array x 2
    
c=np.array([b, b])         
info("c", c)

c has dim 3, shape (2, 2, 3), size 12, and dtype int32:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [28]:
# a row vector
d=np.array([[1,2,3,4]])                
info("d", d)

d has dim 2, shape (1, 4), size 4, and dtype int32:
[[1 2 3 4]]


In [29]:
# Indexing
a=np.array([1,4,2,7,9,5])
print(a[1])
print(a[-2])

4
9


In [30]:
b[0,0] = 10
print(b)

[[10  2  3]
 [ 4  5  6]]


In [31]:
print(a)

[1 4 2 7 9 5]


In [32]:
print(a[1:3])

[4 2]


In [33]:
# reverse
print(a[::-1])  

[5 9 7 2 4 1]


In [34]:
print(b)
print(b[:,0])
print(b[0,:])
print(b[:,1:])

[[10  2  3]
 [ 4  5  6]]
[10  4]
[10  2  3]
[[2 3]
 [5 6]]


In [36]:
# assaining a slice

b[:,1:] = 7
print(b)

[[10  7  7]
 [ 4  7  7]]


In [37]:
print(b[:,0])    
print(b[1,:])   

[10  4]
[4 7 7]


In [11]:
a=np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [8]:
anew = a.reshape(3,3)
info("anew", anew)
info("a", a)

anew has dim 2, shape (3, 3), size 9, and dtype int32:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a has dim 1, shape (9,), size 9, and dtype int32:
[0 1 2 3 4 5 6 7 8]


In [12]:
# one dimensional array
d = np.arange(4)
d

array([0, 1, 2, 3])

In [13]:
# reshaping to 2D row vector (one row, four columns)
dr = d.reshape(1,4)
dr

array([[0, 1, 2, 3]])

In [14]:
# reshaping to 2D column vector (four rows, one column)
dc = d.reshape(4,1)
dc

array([[0],
       [1],
       [2],
       [3]])

In [15]:
info("d", d)

d has dim 1, shape (4,), size 4, and dtype int32:
[0 1 2 3]


In [16]:
info("drow", d[:, np.newaxis])

drow has dim 2, shape (4, 1), size 4, and dtype int32:
[[0]
 [1]
 [2]
 [3]]


In [17]:
info("drow", d[np.newaxis, :])

drow has dim 2, shape (1, 4), size 4, and dtype int32:
[[0 1 2 3]]


In [18]:
info("dcol", d[:, np.newaxis])

dcol has dim 2, shape (4, 1), size 4, and dtype int32:
[[0]
 [1]
 [2]
 [3]]


In [19]:
a=np.random.randint(0, 10, (4,4))
print(a)

[[6 8 8 0]
 [3 5 1 2]
 [6 3 3 2]
 [9 1 2 0]]


In [20]:
# T = transpose method
print(a.T)


[[6 3 6 9]
 [8 5 3 1]
 [8 1 3 2]
 [0 2 2 0]]


In [21]:
a=np.arange(2)
b=np.arange(2,5)
print(f"a has shape {a.shape}: {a}")
print(f"b has shape {b.shape}: {b}")
np.concatenate((a,b))

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]


array([0, 1, 2, 3, 4])

In [22]:
c = np.arange(1,5).reshape(2,2)
print(f"c has shape {c.shape}:", c, sep="\n")

c has shape (2, 2):
[[1 2]
 [3 4]]


In [23]:
np.concatenate((c,c))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [24]:
# Joining arrays horizontally
np.concatenate((c,c), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [31]:
a = np.arange(2)
print(a)
a.reshape(1,2) # to 3rd dimension

[0 1]


array([[0, 1]])

In [32]:
# Then we can catenate arrays: 
print("New row:")
print(np.concatenate((c,a.reshape(1,2))))
print("New column:")
print(np.concatenate((c,a.reshape(2,1)), axis=1))

New row:
[[1 2]
 [3 4]
 [0 1]]
New column:
[[1 2 0]
 [3 4 1]]


In [33]:
np.stack((b,b))

array([[2, 3, 4],
       [2, 3, 4]])

In [34]:
np.stack((b,b), axis=1)

array([[2, 2],
       [3, 3],
       [4, 4]])

In [35]:
d = np.arange(12).reshape(6,2)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [42]:
# Split to two equal arrays
d1, d2 = np.split(d, 2)
print(d1)
print(20*"=")
print(d2)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [43]:
d = np.arange(12).reshape(2,6)
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [46]:
parts = np.split(d, (0,1,), axis=0)
for i, p in enumerate(parts):
    print("part:", i)
    print(p)

part: 0
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part: 1
[]
part: 2
[]
part: 3
[]
